### ISSUE TITLE
Bug on FF

### ISSUE THREAD

**Issue by Nihilop** [zeokku/vue-smoothie#1]
Hello, 

Infinite scroll on firerox :)

**Comment by Lutymane** [comment]
Hello. Yeah, Firefox browser is just a mess. I still didn't figure out, though, if it's just a bug on FF side or there's actually something in the spec about it (which I doubt).

As I investigated negative offset (only vertical for some reason) is counted towards scroll height and as the content wrapper translates up it counts both that negative offset and actual height of the content recursively leading to infinite scrolling.

The workaround for this is to add `position: absolute` for that translated wrapper. I'll make this change.

**Comment by Lutymane** [comment]
Welp, it hasn't been fixed for years T_T
https://bugzilla.mozilla.org/show_bug.cgi?id=1434265
https://bugzilla.mozilla.org/show_bug.cgi?id=1314422

Same behavior:
https://bug1434265.bmoattachments.org/attachment.cgi?id=8946640

And adding `position: absolute` causes weird jump of scroll at the end to 0 in case of top level scroll, which is another bug

**Comment by Lutymane** [comment]
Alright, the vertical scrolling should now be working everywhere correctly on 1.2. 

There's still a problem with horizontal scroll in Omni flavor, but it's of much less importance.

**Comment by Nihilop** [comment]
Nice ! Thanks ♥
